### ISSUE TITLE
installation issue with pip 

### ISSUE THREAD

**Issue by lasekgis** [nextgis/nextgisweb_mapserver#13]
Hi, Houston I have a problem to install nextgisweb_mapserver, any idea how can I fix this, please  ?
I am using Ubuntu 16.04 and Python 2.7.
When I try to to point to MaspScript version I get this:
btaining file:///home/xxxxx/ngw/nextgisweb_mapserver
Requirement already satisfied: nextgisweb in ./nextgisweb (from nextgisweb-mapserver==0.0.dev0) (3.0)
Exception:
Traceback (most recent call last):
  File "/home/xxxxx/ngw/env/local/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/home/xxxxx/ngw/env/local/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 318, in run
    resolver.resolve(requirement_set)
  File "/home/xxxxx/ngw/env/local/lib/python2.7/site-packages/pip/_internal/resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "/home/xxxxx/ngw/env/local/lib/python2.7/site-packages/pip/_internal/resolve.py", line 318, in _resolve_one
    add_req(subreq, extras_requested=available_requested)
  File "/home/xxxxx/ngw/env/local/lib/python2.7/site-packages/pip/_internal/resolve.py", line 275, in add_req
    wheel_cache=self.wheel_cache,
  File "/home/xxxxx/ngw/env/local/lib/python2.7/site-packages/pip/_internal/req/constructors.py", line 288, in install_req_from_req
    if req.url and comes_from.link.netloc in domains_not_allowed:
AttributeError: 'NoneType' object has no attribute 'netloc'

Thanks in advance

**Comment by JogicPogic** [comment]
I have the same problem!

**Comment by lasekgis** [comment]
Thank you for this confirmation... but it seems to me that if i using previous version from the pip (for. ex. pip 9.0), it is working correctly.

**Comment by JogicPogic** [comment]
Yes! Thank you! I downgraded pip to 8.1.2 and NextGIS Web MapServer installed.
